src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuteurRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"nom_prenom"},
 *     errorPath="nom_prenom",
 *     message="Ce nom d'auteur est existe déjà !"
 * )
 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $nom_prenom;

    /**
     * @ORM\Column(type="string", length=1, columnDefinition="ENUM('M', 'F')"))
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\LessThan("today")
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, mappedBy="auteurs", cascade={"persist"})
     */
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livres->removeElement($livre);

        return $this;
    }

    public function __toString()
    {
        return $this->nom_prenom;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function corrigeNationalite()
    {
        $this->nom_prenom = ucfirst($this->nom_prenom);
        $this->nationalite = ucfirst($this->nationalite);
    }
}

src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator as MyValidator; 

/**
 * @ORM\Entity(repositoryClass="App\Repository\LivreRepository")
 */
class Livre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=17)
     * @MyValidator\IsISBN
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="smallint")
     */
    private $nbpages;

    /**
     * @ORM\Column(type="date")
     * @Assert\LessThan("today")
     */
    private $date_de_parution;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Range(
     *          min=0, 
     *          max=20, 
     *          notInRangeMessage = "La note doit être entre {{ min }} et {{ max }}")
     */
    private $note;

    /**
     * @ORM\ManyToMany(targetEntity=Auteur::class, inversedBy="livres", cascade={"persist"})
     */
    private $auteurs;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="livres", cascade={"persist"})
     */
    private $genres;

    public function __construct()
    {
        $this->auteurs = new ArrayCollection();
        $this->genres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getNbpages(): ?int
    {
        return $this->nbpages;
    }

    public function setNbpages(int $nbpages): self
    {
        $this->nbpages = $nbpages;

        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->date_de_parution;
    }

    public function setDateDeParution(\DateTimeInterface $date_de_parution): self
    {
        $this->date_de_parution = $date_de_parution;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    /**
     * @return Collection|Auteur[]
     */
    public function getAuteurs(): Collection
    {
        return $this->auteurs;
    }

    public function addAuteur(Auteur $auteur): self
    {
        if (!$this->auteurs->contains($auteur)) {
            $this->auteurs[] = $auteur;
        }

        return $this;
    }

    public function removeAuteur(Auteur $auteur): self
    {
        $this->auteurs->removeElement($auteur);

        return $this;
    }

    public function setAuteurs(string $auteurs): self
    {
        $this->auteurs = $auteurs;

        return $this;
    }

    public function __toString()
    {
        return $this->titre;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->genres->removeElement($genre);

        return $this;
    }
}

src/Form/LivreType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use App\Entity\Genre;
use App\Entity\Livre;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LivreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('isbn', TextType::class, ['label' => 'ISBN'])
            ->add('titre', TextType::class, ['label' => 'Titre'])
            ->add('nbpages', IntegerType::class)
            ->add('date_de_parution', DateType::class, [
                'label' => 'Date de parution',
                'attr' => [
                    'class' => 'datepicker'
                ],
                'widget' => 'single_text',
                'html5' => false
            ])
            ->add('note', IntegerType::class, ['label' => 'Note'])
            ->add('auteurs', EntityType::class, [
                'label' => 'Auteurs',
                'class' => Auteur::class,
                'multiple' => true,
                'attr' => [
                    'class' => 'input-field'
                ]
            ])
            ->add('genres', EntityType::class, [
                'label' => 'Genres',
                'class' => Genre::class,
                'multiple' => true,
                'required' => true,
                'attr' => [
                    'class' => 'input-field'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livre::class,
        ]);
    }
}

src/Controller/LivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/livre")
 */
class LivreController extends AbstractController
{
    /**
     * @Route("/", name="livre_index", methods={"GET"})
     */
    public function index(LivreRepository $livreRepository): Response
    {
        return $this->render('livre/index.html.twig', [
            'livres' => $livreRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="livre_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($livre);
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="livre_show", methods={"GET"})
     */
    public function show(Livre $livre): Response
    {
        return $this->render('livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="livre_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="livre_delete", methods={"POST"})
     */
    public function delete(Request $request, Livre $livre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $livre->getId(), $request->request->get('_token'))) {
            $entityManager->remove($livre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('livre_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/filtrer/byDatesNote", name="livre_filtrer_dates_note", methods={"GET", "POST"})
     */
    public function filterByDatesNote(Request $request, LivreRepository $livreRepository)
    {
        $formDatesNote = $this->createFormBuilder(null)
            ->setAction($this->generateUrl('livre_filtrer_dates_note'))
            ->add('date_debut', DateType::class, [
                'attr' => [
                    'class' => 'datepicker'
                ],
                'widget' => 'single_text',
                'html5' => false
            ])
            ->add('date_fin', DateType::class, [
                'attr' => [
                    'class' => 'datepicker'
                ],
                'widget' => 'single_text',
                'html5' => false
            ])
            ->add('note_min', IntegerType::class, [
                'required' => false
            ])
            ->add('note_max', IntegerType::class, [
                'required' => false
            ])
            ->getForm();

        $formDatesNote->handleRequest($request);

        if ($formDatesNote->isSubmitted() && $formDatesNote->isValid()) {
            $date_debut = $request->request->get('form')['date_debut'];
            $date_fin = $request->request->get('form')['date_fin'];
            $note_min = $request->request->get('form')['note_min'];
            $note_max = $request->request->get('form')['note_max'];

            $livres = $livreRepository->findByDatesNote($date_debut, $date_fin, $note_min, $note_max);

            return $this->render('livre/index.html.twig', [
                "livres" => $livres
            ]);
        }
        return $this->render('livre/_filtrerByDateNote.html.twig', [
            'form' => $formDatesNote->createView(),
        ]);
    }

    /**
     * @Route("/filtrer/byTitre", name="livre_filtrer_titre", methods={"GET", "POST"})
     */
    public function filterByTitre(Request $request, LivreRepository $livreRepository)
    {
        $formTitre = $this->createFormBuilder(null)
            ->setAction($this->generateUrl('livre_filtrer_titre'))
            ->add('titre', TextType::class)
            ->getForm();

        $formTitre->handleRequest($request);

        if ($formTitre->isSubmitted() && $formTitre->isValid()) {
            $titre = $request->request->get('form')['titre'];

            $livres = $livreRepository->findByLikeTitre($titre);

            return $this->render('livre/index.html.twig', [
                "livres" => $livres
            ]);
        }
        return $this->render('livre/_filtrerByTitre.html.twig', [
            'form' => $formTitre->createView(),
        ]);
    }

    /**
     * @Route("/filtrer/byParite", name="livre_filtrer_parite", methods={"GET", "POST"})
     */
    public function filterByParite(Request $request, LivreRepository $livreRepository)
    {
        $formTitre = $this->createFormBuilder(null)
            ->setAction($this->generateUrl('livre_filtrer_parite'))
            ->add('parite', ChoiceType::class, [
                'choices' => [
                    'Oui' => true
                ],
                'label' => 'Parité Homme/Femme',
                'required' => true
            ])
            ->getForm();

        $formTitre->handleRequest($request);

        if ($formTitre->isSubmitted() && $formTitre->isValid()) {

            $livres = $livreRepository->findByParite();

            return $this->render('livre/index.html.twig', [
                "livres" => $livres
            ]);
        }
        return $this->render('livre/_filtrerByParite.html.twig', [
            'form' => $formTitre->createView(),
        ]);
    }

    /**
     * @Route("/filtrer/byNationalite", name="livre_filtrer_nationalite", methods={"GET", "POST"})
     */
    public function filterByDifferentNationalite(Request $request, LivreRepository $livreRepository)
    {
        $formTitre = $this->createFormBuilder(null)
            ->setAction($this->generateUrl('livre_filtrer_nationalite'))
            ->add('nationalite', ChoiceType::class, [
                'choices' => [
                    'Oui' => true
                ],
                'label' => 'Différent nationalité',
                'required' => true
            ])
            ->getForm();

        $formTitre->handleRequest($request);

        if ($formTitre->isSubmitted() && $formTitre->isValid()) {

            $livres = $livreRepository->findByDifferentNationalite();

            return $this->render('livre/index.html.twig', [
                "livres" => $livres
            ]);
        }
        return $this->render('livre/_filtrerByDifferentNationalite.html.twig', [
            'form' => $formTitre->createView(),
        ]);
    }

    /**
     * @Route("/{id}/note/augmenter", name="livre_note_augmenter", methods={"GET", "POST"})
     */
    public function augmenteNote(Request $request, Livre $livre, EntityManagerInterface $entityManager)
    {

        $livre = $entityManager->getRepository(Livre::class)->find($livre);
        if ($livre) {
            if ($livre->getNote() < 20) {
                $livre->setNote($livre->getNote() + 1);
                $entityManager->flush();
            }
            return $this->redirectToRoute('livre_show', [
                'id' => $livre->getId()
            ]);
        }
    }

    /**
     * @Route("/{id}/note/diminuer", name="livre_note_diminuer", methods={"GET", "POST"})
     */
    public function diminuerNote(Request $request, Livre $livre, EntityManagerInterface $entityManager)
    {

        $livre = $entityManager->getRepository(Livre::class)->find($livre);
        if ($livre) {
            if ($livre->getNote() > 0) {
                $livre->setNote($livre->getNote() - 1);
                $entityManager->flush();
            }
            return $this->redirectToRoute('livre_show', [
                'id' => $livre->getId()
            ]);
        }
    }
}

templates/livre/_delete_form.html.twig
<form method="post" action="{{ path('livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
	<button class="btn tooltipped red darken-1" data-position="bottom" data-tooltip="Supprimer">
		<i class="fas fa-trash"></i>
	</button>
</form>

templates/livre/_filtrerByDateNote.html.twig
{{ form_start(form) }}
<div class="row">
	<div class="col s6">
		{{ form_row(form.date_debut) }}
	</div>
    <div class="col s6">
		{{ form_row(form.date_fin) }}
	</div>
    <div class="col s6">
		{{ form_row(form.note_min) }}
	</div>
	<div class="col s6">
		{{ form_row(form.note_max) }}
	</div>
</div>
<button class="btn">{{ button_label|default('Filtrer') }}</button>
{{ form_end(form) }}

templates/livre/_filtrerByDifferentNationalite.html.twig
{{ form_start(form) }}
<div class="row">
	<div class="col s12">
		{{ form_row(form.nationalite) }}
	</div>
</div>
<button class="btn">{{ button_label|default('Filtrer') }}</button>
{{ form_end(form) }}

templates/livre/_filtrerByParite.html.twig
{{ form_start(form) }}
<div class="row">
	<div class="col s12">
		{{ form_row(form.parite) }}
	</div>
</div>
<button class="btn">{{ button_label|default('Filtrer') }}</button>
{{ form_end(form) }}

templates/livre/_filtrerByTitre.html.twig
{{ form_start(form) }}
<div class="row">
	<div class="col s12">
		{{ form_row(form.titre) }}
	</div>
</div>
<button class="btn">{{ button_label|default('Rechercher') }}</button>
{{ form_end(form) }}

templates/livre/_form.html.twig
{{ form_start(form) }}
<div class="row form">
	<div class="col s6">
		{{ form_row(form.isbn) }}
	</div>
	<div class="col s6">
		{{ form_row(form.titre) }}
	</div>
	<div class="col s6">
		{{ form_row(form.nbpages) }}
	</div>
	<div class="col s6">
		{{ form_row(form.date_de_parution) }}
	</div>
	<div class="col s6">
		{{ form_row(form.note) }}
	</div>
	<div class="col s6">
		{{ form_row(form.auteurs) }}
	</div>
	<div class="col s6">
		{{ form_row(form.genres) }}
	</div>
</div>
<button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Modifier le livre</h1>

		{{ include('livre/_form.html.twig', {'button_label': 'Modifier'}) }}

		<div class="row">
			<div class="col s6 offset-s6">
				<a class="btn" href="{{ path('livre_index') }}">
					<i class="fas fa-clipboard-list"></i>
					Revenir à la liste
				</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre index
{% endblock %}

{% block stylesheets %}
	<style type="text/css">
		table tbody td.table-action {
			display: flex !important;
			justify-content: space-evenly;
		}

		#filtrer .modal {
			height: 70%;
		}
	</style>
{% endblock stylesheets %}

{% block body %}
	<div class="container">
		<div style="display: flex; align-items: center; justify-content: space-between; margin: 1rem 0">
			<h1>
				<i class="fas fa-book"></i>
				Liste livres
			</h1>
			<div class="actions">
				<a class="btn waves-effect waves-light" href="{{ path('livre_new') }}">
					<i class="fas fa-plus"></i>
					Ajouter
				</a>
				<a class="waves-effect waves-light btn modal-trigger" href="#filtrer">
					<i class="fas fa-search"></i>
					Filtrer
				</a>
			</div>
		</div>


		<table class="table striped responsive-table centered">
			<thead>
				<tr>
					<th><i class="fas fa-barcode" style="margin-right: 5px"></i>ISBN</th>
					<th><i class="fas fa-book" style="margin-right: 5px"></i>Titre</th>
					<th><i class="fas fa-file-alt" style="margin-right: 5px"></i>Nombre de pages</th>
					<th><i class="fas fa-calendar-check" style="margin-right: 5px"></i>Date de parution</th>
					<th><i class="fas fa-star" style="margin-right: 5px"></i>Note</th>
					<th><i class="fas fa-user-graduate" style="margin-right: 5px"></i>Auteurs</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for livre in livres %}
					<tr>
						<td>{{ livre.isbn }}</td>
						<td style="width: 25%">{{ livre.titre }}</td>
						<td>{{ livre.nbpages }}</td>
						<td>{{ livre.dateDeParution ? livre.dateDeParution|date('Y-m-d') : '' }}</td>
						<td>{{ livre.note }}</td>
						<td>
							<a class="waves-effect waves-light btn modal-trigger tooltipped" href="{{'#livre-' ~ livre.id}}" data-position="bottom" data-tooltip="Voir ses auteurs">
								<i class="fas fa-user-graduate"></i>
							</a>
						</td>
						<td class="table-action">
							<a class="btn tooltipped" data-position="bottom" data-tooltip="Voir" href="{{ path('livre_show', {'id': livre.id}) }}">
								<i class="fas fa-eye"></i>
							</a>
							<a class="btn tooltipped amber darken-3" data-position="bottom" data-tooltip="Modifier" href="{{ path('livre_edit', {'id': livre.id}) }}">
								<i class="fas fa-edit"></i>
							</a>
							{{ include('livre/_delete_form.html.twig') }}
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="8">Aucun livre trouvé !</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		{% for livre in livres %}
			<!-- Modal Structure -->
			<div id="{{'livre-' ~ livre.id}}" class="modal modal-fixed-footer">
				<div class="modal-content">
					<ul class="collection with-header">
						<li class="collection-header">
							<h4>Auteurs</h4>
						</li>
						{% for auteur in livre.auteurs %}
							<li class="collection-item">
								<div>
									{{ auteur.nomPrenom }}
									<a href="{{ path('auteur_show', {'id': auteur.id}) }}" class="secondary-content">
										<i class="material-icons">send</i>
									</a>
								</div>
							</li>
						{% else %}
							<li class="collection-item">
								Aucun auteur trouvé !
							</li>
						{% endfor %}
					</ul>
				</div>
				<div class="modal-footer">
					<a href="#!" class="modal-close waves-effect waves-green btn-flat red darken-1 white-text">Fermer</a>
				</div>
			</div>
		{% endfor %}

		<!-- Modal Structure -->
		<div id="filtrer" class="modal modal-fixed-footer">
			<div class="modal-content">
				<h4>Filtrer les livres</h4>

				<ul id="tabs-swipe-demo" class="tabs tabs-title" style="margin-bottom: 1rem;">
					<li class="tab col s3">
						<a class="active" href="#test-swipe-1">Titre</a>
					</li>
					<li class="tab col s3">
						<a href="#test-swipe-2">Date de parution et/ou note</a>
					</li>
					<li class="tab col s3">
						<a href="#test-swipe-3">Parité Homme/Femme</a>
					</li>
					<li class="tab col s3">
						<a href="#test-swipe-4">Nationalité</a>
					</li>
				</ul>
				<div id="test-swipe-1" class="col s12">
					{{ render(path('livre_filtrer_titre')) }}
				</div>
				<div id="test-swipe-2" class="col s12">
					{{ render(path('livre_filtrer_dates_note')) }}
				</div>
				<div id="test-swipe-3" class="col s12">
					{{ render(path('livre_filtrer_parite')) }}
				</div>
				<div id="test-swipe-4" class="col s12">
					{{ render(path('livre_filtrer_nationalite')) }}
				</div>
			</div>
			<div class="modal-footer">
				<a href="#!" class="modal-close waves-effect waves-green btn-flat">Fermer</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un livre
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Ajouter un livre</h1>

		{{ include('livre/_form.html.twig') }}

		<div class="row">
			<div class="col s6 offset-s6">
				<a class="btn" href="{{ path('livre_index') }}">
					<i class="fas fa-clipboard-list"></i>
					Revenir à la liste
				</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre
{% endblock %}

{% block body %}
	<div class="container">
		<div class="page row">
			<div class="picture col s6">
				<img width="20%" src="{{ asset('/assets/books.png') }}"/>
				<h3>{{ livre.titre }}</h3>
			</div>
			<div class="info col s6">
				<h4>Informations</h4>
				<table class="table responsive-table info-table">
					<tbody>
						<tr>
							<th>ISBN</th>
							<td>{{ livre.isbn }}</td>
						</tr>
						<tr>
							<th>Titre</th>
							<td>{{ livre.titre }}</td>
						</tr>
						<tr>
							<th>Nombre de pages</th>
							<td>{{ livre.nbpages }}</td>
						</tr>
						<tr>
							<th>Date de parution</th>
							<td>{{ livre.dateDeParution ? livre.dateDeParution|date('d/m/Y') : '' }}</td>
						</tr>
						<tr>
							<th>Note /20</th>
							<td>
								{{ livre.note }}
								<a 
									href="{{ path('livre_note_augmenter', {'id': livre.id}) }}" 
									style="margin-left: 1rem" 
									class="btn tooltipped teal darken-1 {% if livre.note == 20 %} disabled {% endif %}" 
									data-position="bottom" 
									data-tooltip="Augmenter la note"
									>
									<i class="fas fa-plus"></i>
								</a>
								<a 
									href="{{ path('livre_note_diminuer', {'id': livre.id}) }}" 
									class="btn tooltipped red darken-1 {% if livre.note == 0 %} disabled {% endif %}" 
									data-position="bottom" 
									data-tooltip="Diminuer la note">
									<i class="fas fa-minus"></i>
								</a>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col s6 offset-s6">
				<a class="btn" href="{{ path('livre_index') }}">
					<i class="fas fa-clipboard-list"></i>
					Revenir à la liste
				</a>
				<a class="btn amber darken-3" href="{{ path('livre_edit', {'id': livre.id}) }}">
					<i class="fas fa-edit"></i>
					Modifier
				</a>
			</div>
		</div>
		<div class="row">
			<div class="col s6 offset-s6">
				<ul class="collection with-header">
					<li class="collection-header">
						<h5>Auteurs</h5>
					</li>
					{% for auteur in livre.auteurs %}
						<li class="collection-item">
							<div>
								{{ auteur.nomPrenom }}
								<a href="{{ path('auteur_show', {'id': auteur.id}) }}" class="secondary-content">
									<i class="material-icons">send</i>
								</a>
							</div>
						</li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
{% endblock %}