src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuteurRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"nom_prenom"},
 *     errorPath="nom_prenom",
 *     message="Ce nom d'auteur est existe déjà !"
 * )
 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $nom_prenom;

    /**
     * @ORM\Column(type="string", length=1, columnDefinition="ENUM('M', 'F')"))
     */
    private $sexe;

    /**
     * @ORM\Column(type="date")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\LessThan("today")
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, mappedBy="auteurs", cascade={"persist"})
     */
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPrenom(): ?string
    {
        return $this->nom_prenom;
    }

    public function setNomPrenom(string $nom_prenom): self
    {
        $this->nom_prenom = $nom_prenom;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    /**
     * @return Collection|Livre[]
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        $this->livres->removeElement($livre);

        return $this;
    }

    public function __toString()
    {
        return $this->nom_prenom;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function corrigeNationalite()
    {
        $this->nom_prenom = ucfirst($this->nom_prenom);
        $this->nationalite = ucfirst($this->nationalite);
    }
}

src/Form/AuteurType.php
<?php

namespace App\Form;

use App\Entity\Auteur;
use App\Entity\Livre;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_prenom', TextType::class, [
                'label' => 'Nom et Prénom'
            ])
            ->add('sexe', ChoiceType::class, [
                'label' => 'Sexe',
                'choices' => [
                    'Masculin' => 'M',
                    'Feminin' => 'F'
                ],
                'multiple' => false
            ])
            ->add('date_de_naissance', DateType::class, [
                'label' => 'Date de naissance',
                'attr' => [
                    'class' => 'datepicker'
                ],
                'widget' => 'single_text',
                'html5' => false
            ])
            ->add('nationalite', TextType::class, ['label' => 'Nationalité'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Auteur::class,
        ]);
    }
}

src/Controller/AuteurController.php
<?php

namespace App\Controller;

use App\Entity\Auteur;
use App\Form\AuteurType;
use App\Repository\AuteurRepository;
use App\Repository\GenreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/auteur")
 */
class AuteurController extends AbstractController
{
    /**
     * @Route("/", name="auteur_index", methods={"GET"})
     */
    public function index(AuteurRepository $auteurRepository): Response
    {
        return $this->render('auteur/index.html.twig', [
            'auteurs' => $auteurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="auteur_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $auteur = new Auteur();
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($auteur);
            $entityManager->flush();

            return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/new.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="auteur_show", methods={"GET"})
     */
    public function show(Auteur $auteur, GenreRepository $genreRepository): Response
    {
        $genres = $genreRepository->createQueryBuilder('g')
        ->select('DISTINCT g')
        ->innerJoin('g.livres', 'livre')
        ->innerJoin('livre.auteurs', 'a')
        ->andWhere('a.id = :id')
        ->setParameter('id', $auteur->getId())
        ->getQuery()
        ->getResult();

        return $this->render('auteur/show.html.twig', [
            'auteur' => $auteur,
            'genres' => $genres,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="auteur_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AuteurType::class, $auteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('auteur/edit.html.twig', [
            'auteur' => $auteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="auteur_delete", methods={"POST"})
     */
    public function delete(Request $request, Auteur $auteur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$auteur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($auteur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('auteur_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/filtrer/by3Livres", name="auteur_filtrer_3_livres", methods={"GET", "POST"})
     */
    public function filterBy3Livres(Request $request, AuteurRepository $auteurRepository)
    {
        $formLivre = $this->createFormBuilder(null)
            ->setAction($this->generateUrl('auteur_filtrer_3_livres'))
            ->add('livres', ChoiceType::class, [
                'choices' => [
                    'Oui' => true
                ],
                'label' => 'Auteurs ayant écrit dans plus de 3 livres',
                'required' => true
            ])
            ->getForm();

        $formLivre->handleRequest($request);

        if ($formLivre->isSubmitted() && $formLivre->isValid()) {

            $auteurs = $auteurRepository->findBy3Livres();

            return $this->render('auteur/index.html.twig', [
                "auteurs" => $auteurs
            ]);
        }
        return $this->render('auteur/_filtrerBy3Livres.html.twig', [
            'form' => $formLivre->createView(),
        ]);
    }
}

templates/auteur/_delete_form.html.twig
<form method="post" action="{{ path('auteur_delete', {'id': auteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ auteur.id) }}">
    <button class="btn tooltipped red darken-1" data-position="bottom" data-tooltip="Supprimer">
		  <i class="fas fa-trash"></i>
	  </button>
</form>

templates/auteur/_filtrerBy3Livres.html.twig
{{ form_start(form) }}
<div class="row">
	<div class="col s12">
		{{ form_row(form.livres) }}
	</div>
</div>
<button class="btn">{{ button_label|default('Rechercher') }}</button>
{{ form_end(form) }}

templates/auteur/_form.html.twig
{{ form_start(form) }}
<div class="row form">
	<div class="col s6">
		{{ form_row(form.nom_prenom) }}
	</div>
	<div class="col s6">
		{{ form_row(form.date_de_naissance) }}
	</div>
	<div class="col s6">
		{{ form_row(form.nationalite) }}
	</div>
	<div class="col s6">
		{{ form_row(form.sexe) }}
	</div>
</div>
<button class="btn">{{ button_label|default('Créer') }}</button>
{{ form_end(form) }}

templates/auteur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Auteur
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Modifier l'auteur</h1>

		{{ include('auteur/_form.html.twig', {'button_label': 'Modifier'}) }}

		<div class="row">
			<div class="col s6 offset-s6">
				<a class="btn" href="{{ path('auteur_index') }}">
					<i class="fas fa-clipboard-list"></i>
					Revenir à la liste
				</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/auteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteur index
{% endblock %}

{% block stylesheets %}
	<style type="text/css">
		table tbody td.table-action {
			display: flex !important;
			justify-content: space-evenly;
		}
	</style>
{% endblock stylesheets %}

{% block body %}
	<div class="container">
		<div style="display: flex; align-items: center; justify-content: space-between; margin: 1rem 0">
			<h1>
				<i class="fas fa-user-tie"></i>
				Liste auteurs
			</h1>
			<div class="actions">
				<a class="btn waves-effect waves-light" href="{{ path('auteur_new') }}">
					<i class="fas fa-plus"></i>
					Ajouter
				</a>
				<a class="waves-effect waves-light btn modal-trigger" href="#filtrer">
					<i class="fas fa-search"></i>
					Filtrer
				</a>
			</div>
		</div>

		<table class="table striped responsive-table centered">
			<thead>
				<tr>
					<th>
						<i class="fas fa-signature" style="margin-right: 5px"></i>
						Nom Prénom
					</th>
					<th>
						<i class="fas fa-venus-mars" style="margin-right: 5px"></i>
						Sexe
					</th>
					<th>
						<i class="fas fa-calendar-day" style="margin-right: 5px"></i>
						Date de naissance
					</th>
					<th>
						<i class="fas fa-flag" style="margin-right: 5px"></i>
						Nationalité
					</th>
					<th>
						<i class="fas fa-book" style="margin-right: 5px"></i>Livres
					</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for auteur in auteurs %}
					<tr>
						<td>{{ auteur.nomPrenom }}</td>
						<td>
							{% if auteur.sexe == 'M' %}
								<i class="fas fa-mars"></i>
								Homme
							{% else %}
								<i class="fas fa-venus"></i>
								Femme
							{% endif %}
						</td>
						<td>{{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('Y-m-d') : '' }}</td>
						<td>{{ auteur.nationalite }}</td>
						<td>
							<a class="waves-effect waves-light btn modal-trigger tooltipped" data-position="bottom" data-tooltip="Voir ses livres" href="{{'#auteur-' ~ auteur.id}}">
								<i class="fas fa-book"></i>
							</a>
						</td>
						<td class="table-action">
							<a class="btn tooltipped" data-position="bottom" data-tooltip="Voir" href="{{ path('auteur_show', {'id': auteur.id}) }}">
								<i class="fas fa-eye"></i>
							</a>
							<a class="btn tooltipped amber darken-3" data-position="bottom" data-tooltip="Modifier" href="{{ path('auteur_edit', {'id': auteur.id}) }}">
								<i class="fas fa-edit"></i>
							</a>
							{{ include('auteur/_delete_form.html.twig') }}
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="6">Aucun auteur trouvé !</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	{% for auteur in auteurs %}
		<!-- Modal Structure -->
		<div id="{{'auteur-' ~ auteur.id}}" class="modal modal-fixed-footer">
			<div class="modal-content">
				<ul class="collection with-header">
					<li class="collection-header">
						<h4>Livres</h4>
					</li>
					{% for livre in auteur.livres %}
						<li class="collection-item">
							<div>
								{{ livre.titre }}
								<a href="{{ path('livre_show', {'id': livre.id}) }}" class="secondary-content">
									<i class="material-icons">send</i>
								</a>
							</div>
						</li>
					{% else %}
						<li class="collection-item">
							Aucun livre trouvé !
						</li>
					{% endfor %}
				</ul>
			</div>
			<div class="modal-footer">
				<a href="#!" class="modal-close waves-effect waves-green btn-flat red darken-1 white-text">Fermer</a>
			</div>
		</div>
	{% endfor %}
	<!-- Modal Structure -->
	<div id="filtrer" class="modal modal-fixed-footer">
		<div class="modal-content">
			<h4>Filtrer les auteurs</h4>

			<ul id="tabs-swipe-demo" class="tabs tabs-title" style="margin-bottom: 1rem;">
				<li class="tab col s3">
					<a class="active" href="#test-swipe-1">Plus de 3 livres</a>
				</li>
			</ul>
			<div id="test-swipe-1" class="col s12">
				{{ render(path('auteur_filtrer_3_livres')) }}
			</div>
		</div>
		<div class="modal-footer">
			<a href="#!" class="modal-close waves-effect waves-green btn-flat">Fermer</a>
		</div>
	</div>

{% endblock %}

templates/auteur/new.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
	<script>
		document.addEventListener('DOMContentLoaded', function () {
var Calendar = document.querySelectorAll('.datepicker');
M.Datepicker.init(Calendar, {format: 'yyyy-mm-dd'});

var Select = document.querySelectorAll('select');
M.FormSelect.init(Select, {});

});
	</script>
{% endblock javascripts %}

{% block title %}Ajouter un auteur
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Ajouter un auteur</h1>

		{{ include('auteur/_form.html.twig') }}

		<div class="row">
			<div class="col s6 offset-s6">
				<a class="btn" href="{{ path('auteur_index') }}">
					<i class="fas fa-clipboard-list"></i>
					Revenir à la liste
				</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/auteur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Auteur
{% endblock %}

{% block body %}
	<div class="container">
		<div class="page row">
			<div class="picture col s6">
				{% if auteur.sexe == 'M' %}
					<img width="20%" src="{{ asset('/assets/man.png') }}"/>
				{% else %}
					<img width="20%" src="{{ asset('/assets/woman.png') }}"/>
				{% endif %}
				<h3>
					{% if auteur.sexe == 'M' %}
						Mr.
					{% else %}
						Mme.
					{% endif %}
					{{ auteur.nomPrenom }}
				</h3>
			</div>
			<div class="info col s6">
				<h4>Informations</h4>
				<table class="table responsive-table info-table">
					<tbody>
						<tr>
							<th>Sexe</th>
							<td>
								{% if auteur.sexe == 'M' %}
									Homme
								{% else %}
									Femme
								{% endif %}
							</td>
						</tr>
						<tr>
							<th>Date de naissance</th>
							<td>{{ auteur.dateDeNaissance ? auteur.dateDeNaissance|date('d/m/Y') : '' }}</td>
						</tr>
						<tr>
							<th>Nationalité</th>
							<td>{{ auteur.nationalite }}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col s6 offset-s6">
				<a class="btn" href="{{ path('auteur_index') }}">
					<i class="fas fa-clipboard-list"></i>
					Revenir à la liste
				</a>
				<a class="btn amber darken-3" href="{{ path('auteur_edit', {'id': auteur.id}) }}">
					<i class="fas fa-edit"></i>
					Modifier
				</a>
			</div>
		</div>
		<div class="row">
			<div class="col s6">
				<ul class="collection with-header">
					<li class="collection-header">
						<h5>Ses livres</h5>
					</li>
					{% for livre in auteur.livres %}
						<li class="collection-item">
							<div>
								{{ livre.titre }}
								<a href="{{ path('livre_show', {'id': livre.id}) }}" class="secondary-content">
									<i class="material-icons">send</i>
								</a>
							</div>
						</li>
					{% endfor %}
				</ul>
			</div>
			<div class="col s6">
				<ul class="collection with-header">
					<li class="collection-header">
						<h5>Genres <sup>(laquelles écrit au moins un livre)</sup></h5>
					</li>
					{% for genre in genres %}
						<li class="collection-item">
							<div>
								{{ genre.nom }}
								<a href="{{ path('genre_show', {'id': genre.id}) }}" class="secondary-content">
									<i class="material-icons">send</i>
								</a>
							</div>
						</li>
					{% else %}
                        <li class="collection-item">
                            Aucun genre trouvé !
                        </li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
{% endblock %}